
import LocalizedStrings from 'react-native-localization';

export let strings = new LocalizedStrings({


  en:{
Login	:"Login",
Signup	:"Signup",
HireFreelancer	:"Hire Freelancer",
Message	:"Message",
WorkHistory	:"Work History",
Feedback	:"Feedback",
Summary	:"Summary",
MyJobs	:"My Jobs",
Proposal	:"Proposal",
Workinprogress	: "Work in progress",
Budget 	:"Budget",
StartDate	:"Start Date",
EndDate	:"End Date",
Thanks	:"Thanks",
Settings	:"Settings",
Messages	:"Messages",
Jobs	:"Jobs",
and	:"and",
Invitations	:"Invitations",
Notifications	:"Notifications",
Language :"Language   ",

Skill	:"Skill",
MyAccount	:"My Account",

SubmitProposal	:"Submit Proposal",
SelectAccount:"Select Account",
Selectaccounttype	:"Select account type",
Iwanttohirefreelancer	:"I want to hire freelancer",
Iwanttoworkwith	:"I want to work with",
CreateAnAccount:"Create An Account",
Alreadyhaveanaccount	:"Already have an account",
Hire	:"Hire",
MakePayment	:"Make Payment",
CreateMilestones	:"Create Milestones",
Homepage	:"Homepage",
Categories	:"Categories",
Websites	:"Websites",


Verificationcode:"VERIFICATION CODE",
Resentotp:"Resent Otp",
Changeno:"Change Number",
Enterotp:"Enter the four digit code sent to you at",


//keshav
Logout:"Log Out",
Signin:"SIGN IN",
Submit:"SUBMIT",
Mobilenumber:"Mobile Number",

Gotoprofile:"Go To Profile",
About:"About",
MyBalance:"My Balance",
Jobs:"JOBS",
FindFreelancer:"FIND FREELANCER",
FindWorks:"Find Works",
MyPayment:"My Payment",
MyProject:"My Project",

Payment:"Payment",
Title:"Title",
Country:"Country",
Budget:"Budget",
Date:"Date",
Status:"Status",
Description:"Description",
Jobdetail:"Job Detail",

Profile:"Profile",
Username:"User Name",
Emailaddress:"Email Address",
AboutMe	:"About Me",
Usertype:"User Type",
Category:"Category",
Skills:"Skills",
Cv:"CV",
IdProf:"Identity Proof",
Done:"Done",
City:"City",
Startenddate:"Start & End Date",

Freelancerdetail:"Freelancer Details",
Email:"Email",
Name:"Name",
Shortbio:"Short Bio",

AddJob:"Add Job",
Subcategory:"Sub Category",
Milestonelist:"Milestone List",
Projectlist:"Project List",
Amount:"Amount",
Freelancername:"Freelancer Name",
FEEDstring : "FEED",
FAVOURITEstring : "FAVOURITE",
Freelancerstring : "Freelancer",
NoRequestFound : "No Request Found",
Searchstring:"Search",
FixedPrice : "Fixed Price",
Accept : "Accept",
Reject : "Reject",
Hirefreelancer : "Hire freelancer"

  },



  
ar:{
  Login	:" تسجيل الدخول",
  Signup	:"سجل",
  HireFreelancer	:"استئجار لحسابهم الخاص",
  Message	:"رسالة",
  WorkHistory	:"تاريخ العمل",
  Feedback	:"ردود الفعل",
  Summary	:"ملخص",
  MyJobs	:"وظائفي",
  Proposal	:"اقتراح",
  Workinprogress	:"أعمال جارية",
  Budget 	:"ميزانية",
  StartDate	:"تاريخ البدء",
  EndDate	:"تاريخ الانتهاء",
  Thanks	:"شكر",
  Settings	:"الإعدادات",
  Messages	:"رسائل",
  Jobs	:"وظائف",
  and	:"و",
  Invitations	:"دعوات",
  Notifications	:"إخطارات",
  Language:"لغة   ",
  Skill	:"مهارة",
  MyAccount	:"حسابي",
 
  SubmitProposal	:"تقديم الاقتراح",
  
  SelectAccount:"حدد حساب",
  Selectaccounttype	:"اختر نوع الحساب",
  Iwanttohirefreelancer	:"اريد توظيف المستقل",
  Iwanttoworkwith	:"اريد ان اعمل مع",
  CreateAnAccount:"انشئ حساب",
  Alreadyhaveanaccount	:"هل لديك حساب",
  Hire :"توظيف",
  MakePayment	:"قم بالدفع",
  CreateMilestones	:"إنشاء معالم",
  Homepage	:"الصفحة الرئيسية",
  Categories	:"الاقسام",
  Websites	:"المواقع",

  Verificationcode:"شيفرة التأكيد",
  Resentotp:"استياء اوت",
  Enterotp:"أدخل الرمز المكون من أربعة أرقام الذي تم إرساله إليك على",
  Changeno:"تغيير رقم",

  Logout:"الخروج",
  Submit:"خضع",
  Signin:"تسجيل الدخول",
  Mobilenumber:"رقم الهاتف المحمول",

  Gotoprofile:"اذهب إلى الملف الشخصي",
  About:"حول",
  
  MyBalance:"رصيدي",
  Jobs:"وظائف",
  FindFreelancer:"ابحث عن مترجم",
  FindWorks:"البحث عن الأشغال",
  MyPayment:"مدفوعاتى",
  MyProject:"مشروعي",

  Payment:"دفع",
Title:"عنوان",
Country:"بلد",
Budget:"ميزانية",
Date:"تاريخ",
Status:"الحالة",
Description:"وصف",
Jobdetail:"تفاصيل المهمة",

Profile:"الملف الشخصي",
Username:"اسم المستخدم",
Emailaddress:"عنوان بريد الكتروني",
AboutMe	:"عني",
Usertype:"نوع المستخدم",
Category:"الفئة",
Skills:"مهارات",
Cv:"السيرة الذاتية",
IdProf:"إثبات الهوية",
Done:"فعله",
Startenddate:"تاريخ البدء والانتهاء",
City:"مدينة",


Freelancerdetail:"تفاصيل مستقلة",
Email:"البريد الإلكتروني",
Name:"اسم",
Shortbio:"السيرة الذاتية القصيرة",
AddJob:"أضف الوظيفة",
Subcategory:"فرعية",

Milestonelist:"قائمة المعالم",
Projectlist:"قائمة المشروع",
Amount:"كمية",

Freelancername:"اسم حر",
FEEDstring : "تغذية",
FAVOURITEstring : "مفضل",
Freelancerstring : "مستقل",
NoRequestFound : "لم يتم العثور على طلب",
Searchstring:"بحث",
FixedPrice : "سعر ثابت",
Accept : "قبول",
Reject : "رفض",
Hirefreelancer : "استئجار المستقل"


}
});
export default strings;
