
import LocalizedStrings from 'react-native-localization';

export let strings = new LocalizedStrings({


  en:{
Login	:"Login",
Signup	:"Signup",
HireFreelancer	:"Hire Freelancer",
Message	:"Message",
WorkHistory	:"Work History",
Feedback	:"Feedback",
Summary	:"Summary",
MyJobs	:"My Jobs",
Proposal	:"Proposal",
Workinprogress	: "Work in progress",
Budget 	:"Budget",
StartDate	:"Start Date",
EndDate	:"End Date",
Thanks	:"Thanks",
Settings	:"Settings",
Messages	:"Messages",
Jobs	:"Jobs",
and	:"and",
Invitations	:"Invitations",
Notifications	:"Notifications",
Language :"Language   ",

Skill	:"Skill",
MyAccount	:"My Account",

SubmitProposal	:"Submit Proposal",
SelectAccount:"Select Account",
Selectaccounttype	:"Select account type",
Iwanttohirefreelancer	:"I want to hire freelancer",
Iwanttoworkwith	:"I want to work with",
CreateAnAccount:"Create An Account",
Alreadyhaveanaccount	:"Already have an account",
Hire	:"Hire",
MakePayment	:"Make Payment",
CreateMilestones	:"Create Milestones",
Homepage	:"Homepage",
Categories	:"Categories",
Websites	:"Websites",
CreateProject	:"CREATE PROJECT",


Verificationcode:"VERIFICATION CODE",
Resentotp:"Resend OTP",
Changeno:"Change Number",
Enterotp:"Enter the four digit code sent to you at",


//keshav
Logout:"Log Out",
Signin:"SIGN IN",
Submit:"SUBMIT",
Mobilenumber:"Mobile Number",

Gotoprofile:"Go To Profile",
About:"About",
MyBalance:"My Balance",
Jobs:"JOBS",
FindFreelancer:"FIND FREELANCER",
FindWorks:"Find Works",
MyPayment:"My Payment",
MyProject:"My Project",

Payment:"Payment",
Title:"Title",
Country:"Country",
Budget:"Budget",
Date:"Date",
Status:"Status",
Description:"Description",
Jobdetail:"Job Detail",

Profile:"Profile",
Username:"User Name",
Emailaddress:"Email Address",
AboutMe	:"About Me",
Usertype:"User Type",
Category:"Category",
Skills:"Skills",
Cv:"CV",
IdProf:"Identity Proof",
Done:"Done",
City:"City",
Startenddate:"Start & End Date",

Freelancerdetail:"Freelancer Details",
Email:"Email",
Name:"Name",
Shortbio:"Short Bio",

AddJob:"Add Job",
Subcategory:"Sub Category",
Milestonelist:"Milestone List",
Projectlist:"Project List",
Amount:"Amount",
Freelancername:"Freelancer Name",
FEEDstring : "FEED",
FAVOURITEstring : "FAVOURITE",
Freelancerstring : "Freelancer",
NoRequestFound : "No Request Found",
Searchstring:"Search",
FixedPrice : "Fixed Price",
Accept : "Accept",
Reject : "Reject",
Hirefreelancer : "Hire freelancer",
EnterMobileNumber : "Enter Mobile Number",
EnterValidMobileNumber : "Enter Valid Mobile Number",
OTPSentSuccessfully : "OTP Sent Successfully",
NetworkError : "Network Error",
GoToProjects : "Go To Projects",
SelectCitystring : "Select City",
SelectCategorystring : "Select Category",
Enteramount : "Enter amount",
Requestaccpetsuccessfully	:"Request Accepted Successfully",
RequestReject	:"Request Rejected",
Enterskills : "Enter skills",
SubmitSuccessfully	:"Submit Successfully",
PleaseEnterFeedback	:"Please Enter Feedback",
Fillallrequireddetails : "Fill all required details",
JobAddedSuccessfully : "Job added successfully",
AnErrorOccured : "An Error Occured",
RequestSendSuccessfully : "Request send successfully",
AlreadySentRequest : "Already sent request",
HiredSuccessfully : "Hired Successfully",
DueDate : "Due Date",
PleaseEnterAmount : "Please Enter Amount",
PleaseentervalidDueDate : "Please enter valid Due Date",
PleaseenterDescription : "Please enter Description",
MilestoneCreatedSuccessfully : "Milestone Created Successfully",
ProfileUpdatedSuccessfully : "Profile Updated Successfully",
Pleasefillalldetails : "Please fill all details",
Pleaseselectvalidfileformat : "Please select valid file format",
Pleaseentervalidemail : "Please enter valid email",
Addskills : "Add skills",
JobAddedtoFavouritesSuccessfully : "Job added to favourites successfully",
ProjectCreatedSuccessfully : "Project Created Successfully",
JobRemovedFromFavoritesSuccessfully : "Job Removed From Favourites Successfully",
NomessagesFound: "No Messages Found",
Invalidenddate : "Invalid end date",
ExitApp:"Exit App",
DoyouwanttoExittheapplication: "Do you want to Exit the application?",
Cancel : "CANCEL",
Submit : "SUBMIT",
Writeareview : "Write a review....."
  },



  
ar:{
  cancel : "إلغاء",
  DoyouwanttoExittheapplication: "هل تريد الخروج من التطبيق؟",
  ExitApp : "الخروج من التطبيق",
  ProjectCreatedSuccessfully : "تم إنشاء المشروع بنجاح",
  JobAddedtoFavouritesSuccessfully : "الوظيفة المضافة إلى المفضلة بنجاح",
  Addskills : "إضافة المهارات",
  MilestoneCreatedSuccessfully : "معلم خلقت بنجاح",
  PleaseenterDescription : "يرجى إدخال الوصف",
  PleaseentervalidDueDate : "الرجاء إدخال تاريخ الاستحقاق الساري",
  PleaseEnterAmount : "يرجى إدخال المبلغ",
  DueDate : "تاريخ الاستحقاق",
  HiredSuccessfully : "استأجر بنجاح",
  AlreadySentRequest : "تم إرسال الدعوة مسبقا",
  RequestSendSuccessfully : "طلب إرسال بنجاح",
  AnErrorOccured : "حدث خطأ",
  JobAddedSuccessfully : "الوظيفة المضافة بنجاح",
  Fillallrequireddetails : "املأ جميع التفاصيل المطلوبة",
  SubmitSuccessfully	:"يقدم بنجاح",
  PleaseEnterFeedback	:"يرجى إدخال ملاحظات",
  Enterskills : "أدخل المهارات",
  Requestaccpetsuccessfully	:"تم قبول الطلب بنجاح",
  RequestReject	:"طلب رفض",
  Enteramount : "أدخل المبلغ",
  SelectCategorystring : "اختر الفئة",
  SelectCitystring : "اختر مدينة",
  GoToProjects : "الذهاب إلى المشاريع",
  NetworkError : "خطأ في الشبكة",
  OTPSentSuccessfully : "OTP تم إرساله بنجاح",
  EnterValidMobileNumber : "ادخل رقم هاتف خلوي ساري المفعول",
  EnterMobileNumber : "أدخل رقم الجوال",
  Login	:" تسجيل الدخول",
  Signup	:"سجل",
  HireFreelancer	:"استئجار لحسابهم الخاص",
  Message	:"رسالة",
  WorkHistory	:"تاريخ العمل",
  Feedback	:"ردود الفعل",
  Summary	:"ملخص",
  MyJobs	:"وظائفي",
  Proposal	:"اقتراح",
  Workinprogress	:"أعمال جارية",
  Budget 	:"ميزانية",
  StartDate	:"تاريخ البدء",
  EndDate	:"تاريخ الانتهاء",
  Thanks	:"شكر",
  Settings	:"الإعدادات",
  Messages	:"رسائل",
  Jobs	:"وظائف",
  and	:"و",
  Invitations	:"دعوات",
  Notifications	:"إخطارات",
  Language:"لغة   ",
  Skill	:"مهارة",
  MyAccount	:"حسابي",
 
  SubmitProposal	:"تقديم الاقتراح",
  
  SelectAccount:"حدد حساب",
  Selectaccounttype	:"اختر نوع الحساب",
  Iwanttohirefreelancer	:"اريد توظيف المستقل",
  Iwanttoworkwith	:"اريد ان اعمل مع",
  CreateAnAccount:"انشئ حساب",
  Alreadyhaveanaccount	:"هل لديك حساب",
  Hire :"توظيف",
  MakePayment	:"قم بالدفع",
  CreateMilestones	:"إنشاء معالم",
  Homepage	:"الصفحة الرئيسية",
  Categories	:"الاقسام",
  Websites	:"المواقع",

  Verificationcode:"شيفرة التأكيد",
  Resentotp:"استياء اوت",
  Enterotp:"أدخل الرمز المكون من أربعة أرقام الذي تم إرساله إليك على",
  Changeno:"تغيير رقم",

  Logout:"الخروج",
  Submit:"خضع",
  Signin:"تسجيل الدخول",
  Mobilenumber:"رقم الهاتف المحمول",

  Gotoprofile:"اذهب إلى الملف الشخصي",
  About:"حول",
  
  MyBalance:"رصيدي",
  Jobs:"وظائف",
  FindFreelancer:"ابحث عن مترجم",
  FindWorks:"البحث عن الأشغال",
  MyPayment:"مدفوعاتى",
  MyProject:"مشروعي",

  Payment:"دفع",
Title:"عنوان",
Country:"بلد",
Budget:"ميزانية",
Date:"تاريخ",
Status:"الحالة",
Description:"وصف",
Jobdetail:"تفاصيل المهمة",

Profile:"الملف الشخصي",
Username:"اسم المستخدم",
Emailaddress:"عنوان بريد الكتروني",
AboutMe	:"عني",
Usertype:"نوع المستخدم",
Category:"الفئة",
Skills:"مهارات",
Cv:"السيرة الذاتية",
IdProf:"إثبات الهوية",
Done:"فعله",
Startenddate:"تاريخ البدء والانتهاء",
City:"مدينة",


Freelancerdetail:"تفاصيل مستقلة",
Email:"البريد الإلكتروني",
Name:"اسم",
Shortbio:"السيرة الذاتية القصيرة",
AddJob:"أضف الوظيفة",
Subcategory:"فرعية",

Milestonelist:"قائمة المعالم",
Projectlist:"قائمة المشروع",
Amount:"كمية",

Freelancername:"اسم حر",
FEEDstring : "تغذية",
FAVOURITEstring : "مفضل",
Freelancerstring : "مستقل",
NoRequestFound : "لم يتم العثور على طلب",
Searchstring:"بحث",
FixedPrice : "سعر ثابت",
Accept : "قبول",
Reject : "رفض",
Hirefreelancer : "استئجار المستقل",
CreateProject	:"خلق المشروع",
ProfileUpdatedSuccessfully : "تم تحديث الملف الشخصي بنجاح",
Pleasefillalldetails : "يرجى ملء جميع التفاصيل",
Pleaseselectvalidfileformat : " يرجى تحديد تنسيق ملف صالح",
Pleaseentervalidemail : "الرجاء إدخال بريد إلكتروني صحيح",
JobRemovedFromFavoritesSuccessfully : "تمت إزالة المهمة من المفضلة بنجاح",
NomessagesFound: "لا توجد رسائل",
Invalidenddate : "تاريخ غير صالح",
Cancel : "إلغاء",
Submit : "خضع",
Writeareview : "أكتب مراجعة"



}
});
export default strings;
