import React, {Component} from 'react';


export default class Constants  {
  apiUrl  = "http://zaraf.org/freelancerWeb/api";
  background =  require('../images/bg.png');
  logo = require('../images/1.png');
  emailicon = require('../images/email.png');
  passwordIcon = require('../images/password.png');
  googleicon = require('../images/gmail.png');
  fbicon =  require('../images/fb.png');
  backicon = require('../images/top_back.png');
  phoneIcon = require('../images/phone.png');
  loginbg = require('../images/bg03.png');
  menuicon = require('../images/menu.png');
  searchicon = require('../images/search.png');
  cardimage = require('../images/home_img.png');
  defaultImage = require('../images/profile.png');
  logoutIcon =  require('../images/logout.png');
  shareIcon =  require('../images/share.png');
  starIcon =  require('../images/star.png');
  homeIcon =  require('../images/home.png');
  offerIcon =  require('../images/offer.png');
  favIcon =  require('../images/fav.png');
  creditIcon =  require('../images/credits.png');
  helpIcon =  require('../images/help.png');
  notificationIcongrey =  require('../images/notification_gray.png');
  notificationIcon =  require('../images/notification.png');
  toggleIcon=  require('../images/off.png');
  cameraIcon=  require('../images/cemra.png');
  downIcon=  require('../images/down.png');
  upIcon=  require('../images/up.png');
  messagesIcon=  require('../images/message.png');
  paymentIcon=  require('../images/my_balance.png');
  searchFreelancerIcon=  require('../images/search2.png');
  projectsIcon=  require('../images/my_job.png');
  accountIcon=  require('../images/account.png');
  aboutIcon=  require('../images/about.png');
  settingsIcon =  require('../images/setting.png');
  feedbackIcon =  require('../images/feedback.png');
  notificationIcon = require('../images/notifications2.png');
  balanceIcon=  require('../images/my_balance.png');
  heartIcon=  require('../images/heart.png');
  heartIconfilled=  require('../images/heartfilled.png');
  clockIcon=  require('../images/clock.png');
  editIcon=  require('../images/edit2.png');
  closeIcon=  require('../images/close.png');
  workIcon=  require('../images/find_work.png');
  addIcon=  require('../images/add.png');
  nextIcon=  require('../images/list_next.png');
  notifyIcon= require('../images/notification2.png');
langIcon= require('../images/language.png');
volumeIcon= require('../images/volume.png');
settingIcon= require('../images/setting.png');
fillrdrIcon= require('../images/filledr.png');
unfilledrIcon= require('../images/unfilledr.png');
notificationIcon= require('../images/notification.png');
starIcon= require('../images/filled_star.png');
starUnfilledIcon= require('../images/stroke_star.png');
cameraIcon= require('../images/camera.png');
attachIcon= require('../images/attach.png');
client = 0;
freelancer = 0;

}