# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'freelancetest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for freelancetest

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'freelancetest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'freelancetestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'freelancetest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for freelancetest-tvOS

end
